/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Response } from "./response";
import { Expose, Type } from "class-transformer";

/**
 * A list of responses from multiple Smartcar endpoints
 */
export class BatchResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Response })
    @Expose({ name: "responses" })
    @Type(() => Response)
    responses?: Response[];
}
