/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class BatteryCapacity extends SpeakeasyBase {
    /**
     * The total capacity of the vehicle's battery (in kilowatt-hours).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "capacity" })
    capacity?: number;
}
