/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum ChargeActionAction {
    Start = "START",
    Stop = "STOP",
}

export class ChargeAction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: ChargeActionAction;
}
