/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ChargeLimit extends SpeakeasyBase {
    /**
     * The level at which the vehicle should stop charging and be considered fully charged (in percent).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "limit" })
    limit?: number;
}
