/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * returns the wattage of the charger measured by the vehicle.
 */
export class ChargeWattage extends SpeakeasyBase {
    /**
     * The wattage of the charger measured by the vehicle.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "wattage" })
    wattage?: number;
}
