/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The direction the vehicle is traveling.
 */
export enum CompassDirection {
    N = "N",
    Ne = "NE",
    E = "E",
    Se = "SE",
    S = "S",
    Sw = "SW",
    W = "W",
    Nw = "NW",
}

/**
 * returns the compass heading of a Tesla.
 */
export class Compass extends SpeakeasyBase {
    /**
     * The direction the vehicle is traveling.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "direction" })
    direction?: CompassDirection;

    /**
     * The direction the vehicle is traveling (in degrees).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "heading" })
    heading?: number;
}
