/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Header extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sc-data-age" })
    scDataAge?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sc-unit-system" })
    scUnitSystem?: string;
}
