/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A list of vehicles
 */
export class Location extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "latitude" })
    latitude: number;

    @SpeakeasyMetadata()
    @Expose({ name: "longitude" })
    longitude: number;
}
