/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum SuccessResponseStatus {
    Success = "SUCCESS",
    Failed = "FAILED",
}

/**
 * return Success Response
 */
export class SuccessResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: SuccessResponseStatus;
}
