/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A vehicle’s manufacturer identifier.
 */
export class VinInfo extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "vin" })
    vin?: string;
}
