/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class BatchRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=vehicle_id" })
    vehicleId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: string[];
}

export class BatchResponse extends SpeakeasyBase {
    /**
     * A list of responses from multiple Smartcar endpoints
     */
    @SpeakeasyMetadata()
    batchResponse?: shared.BatchResponse;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
